# Generated by Django 4.2.30 on 2026-05-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='page_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Processing', 'Processing'), ('Failed', 'Failed'), ('Downloaded', 'Downloaded')], default='Completed', max_length=20),
        ),
    ]
