# Generated by Django 4.2.30 on 2026-05-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(choices=[('sales_forecast', 'Sales Forecast'), ('churn_risk', 'Customer Churn Risk'), ('risk_analysis', 'Risk Analysis'), ('anomaly_detection', 'Anomaly Detection')], max_length=30)),
                ('input_parameters', models.JSONField(default=dict)),
                ('prediction_results', models.JSONField(default=dict)),
                ('metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
